locals {
  # ---------- HealthyHostCount ----------
  healthy_defs = [
    for key, lb in var.load_balancers : {
      key        = "${key}_healthy"
      # add "-alb-" so it's obvious this is an ALB alarm
      alarm_name = "${var.resource_name_prefix}-${lb.name}-alb-unhealthyhost-high-5min"
      topic_arn  = var.sns_topics.healthy_host
      dimensions = {
        LoadBalancer = lb.lb_arn_suffix
      }
    }
  ]
  healthy_map = { for d in local.healthy_defs : d.key => d }

  # ---------- HTTPCode_Target_5XX_Count ----------
  target_5xx_defs = [
    for key, lb in var.load_balancers : {
      key        = "${key}_target5xx"
      alarm_name = "${var.resource_name_prefix}-${lb.name}-alb-HTTPCode_Target_5XX_Count-high-5min"
      topic_arn  = var.sns_topics.target_5xx
      dimensions = {
        LoadBalancer = lb.lb_arn_suffix
      }
    }
  ]
  target_5xx_map = { for d in local.target_5xx_defs : d.key => d }

  # ---------- HTTPCode_ELB_5XX_Count ----------
  elb_5xx_defs = [
    for key, lb in var.load_balancers : {
      key        = "${key}_elb5xx"
      alarm_name = "${var.resource_name_prefix}-${lb.name}-alb-HTTPCode_ELB_5XX_Count-high-5min"
      topic_arn  = var.sns_topics.elb_5xx
      dimensions = {
        LoadBalancer = lb.lb_arn_suffix
      }
    }
  ]
  elb_5xx_map = { for d in local.elb_5xx_defs : d.key => d }
}


# =============== HealthyHostCount (ALB “up/down”) ===================

resource "aws_cloudwatch_metric_alarm" "healthy_host" {
  for_each = local.healthy_map

  alarm_name        = each.value.alarm_name
  alarm_description = "ALB unhealthy host high (HealthyHostCount < ${var.healthy_min_hosts})"

  namespace          = "AWS/ApplicationELB"
  metric_name        = "HealthyHostCount"
  statistic          = "Minimum"
  period             = var.period_seconds
  evaluation_periods = var.evaluation_periods

  threshold           = var.healthy_min_hosts
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = var.treat_missing_data
  unit                = "Count"

  dimensions    = each.value.dimensions
  alarm_actions = [each.value.topic_arn]

  tags = var.tags
}

# =============== HTTPCode_Target_5XX_Count ===================

resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  for_each = local.target_5xx_map

  alarm_name        = each.value.alarm_name
  alarm_description = "ALB target 5XX count high (Sum >= ${var.target_5xx_count_threshold} in ${var.period_seconds}s)"

  namespace          = "AWS/ApplicationELB"
  metric_name        = "HTTPCode_Target_5XX_Count"
  statistic          = "Sum"
  period             = var.period_seconds
  evaluation_periods = var.evaluation_periods

  threshold           = var.target_5xx_count_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = var.treat_missing_data
  unit                = "Count"

  dimensions    = each.value.dimensions
  alarm_actions = [each.value.topic_arn]

  tags = var.tags
}

# =============== HTTPCode_ELB_5XX_Count ===================

resource "aws_cloudwatch_metric_alarm" "elb_5xx" {
  for_each = local.elb_5xx_map

  alarm_name        = each.value.alarm_name
  alarm_description = "ALB 5XX generated by ALB high (Sum >= ${var.elb_5xx_count_threshold} in ${var.period_seconds}s)"

  namespace          = "AWS/ApplicationELB"
  metric_name        = "HTTPCode_ELB_5XX_Count"
  statistic          = "Sum"
  period             = var.period_seconds
  evaluation_periods = var.evaluation_periods

  threshold           = var.elb_5xx_count_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = var.treat_missing_data
  unit                = "Count"

  dimensions    = each.value.dimensions
  alarm_actions = [each.value.topic_arn]

  tags = var.tags
}
